<a href="https://colab.research.google.com/github/PrashantDandriyal/Udacity-Introduction-to-TensorFlow/blob/master/RBG_function_approximation_try.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf

import numpy as np


In [0]:
import logging
logger = tf.get_logger()
logger.setLevel(logging.ERROR)

In [4]:
R    = np.array([-4, -10,  0,  8, 15, 22,  3],  dtype=float)
B    = np.array([4, -10,  0,  8, 15, 5,  1],  dtype=float)
G    = np.array([0, -10,  0,  8, 15, 2,  38],  dtype=float)
RBG_list = [[R,B,G]]
RBG = np.empty((7,3), float)

Y    = np.array([0, -30, 0, 24, 45, 29, 42],  dtype=float)

for i,c in enumerate(R):
  np.append(RBG,[R[i],B[i], G[i]]) 
  #RBG[i] = R[i]
  print("R={} B = {} G ={} i={}".format(R[i],B[i],G[i],i))
  

R=-4.0 B = 4.0 G =0.0 i=0
R=-10.0 B = -10.0 G =-10.0 i=1
R=0.0 B = 0.0 G =0.0 i=2
R=8.0 B = 8.0 G =8.0 i=3
R=15.0 B = 15.0 G =15.0 i=4
R=22.0 B = 5.0 G =2.0 i=5
R=3.0 B = 1.0 G =38.0 i=6


In [5]:
print(type(RBG))
print(RBG.shape[0])
print(RBG.shape[1])
print(RBG)

<class 'numpy.ndarray'>
7
3
[[4.4943389e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


In [1]:
hidden = tf.keras.layers.Dense(units=2, input_shape=[3])
#hidden = tf.keras.layers.Flatten(input_shape=(1, 3, 1))
output = tf.keras.layers.Dense(units=1)

model = tf.keras.Sequential([hidden, output])
model.compile(loss='mean_squared_error', optimizer=tf.keras.optimizers.Adam(0.1))
history = model.fit(RBG,Y, epochs=500, verbose=False)
print("Finished training the model")


NameError: ignored

In [0]:
import matplotlib.pyplot as plt
plt.xlabel('Epoch Number')
plt.ylabel("Loss Magnitude")
plt.plot(history.history['loss'])